from typing import Dict, List

# Table configuration for business columns
BUSINESS_COLUMNS: Dict[str, List[str]] = {
    "PROVIDER_NPI": [
        "ENTITY_TYPE_CODE", "REPLACEMENT_NPI", "EMPLOYER_IDENTIFICATION_NUMBER", "PROVIDER_ORGANIZATION_NAME",
        "PROVIDER_LAST_NAME", "PROVIDER_FIRST_NAME", "PROVIDER_MIDDLE_NAME", "PROVIDER_NAME_PREFIX_TEXT", 
        "PROVIDER_NAME_SUFFIX_TEXT", "PROVIDER_CREDENTIAL_TEXT", "PROVIDER_OTHER_ORGANIZATION_NAME", 
        "PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE", "PROVIDER_OTHER_LAST_NAME", "PROVIDER_OTHER_FIRST_NAME", 
        "PROVIDER_OTHER_MIDDLE_NAME", "PROVIDER_OTHER_NAME_PREFIX_TEXT", "PROVIDER_OTHER_NAME_SUFFIX_TEXT", 
        "PROVIDER_OTHER_CREDENTIAL_TEXT", "PROVIDER_OTHER_LAST_NAME_TYPE_CODE", "PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS",
        "PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS", "PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME", 
        "PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME", "PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE", 
        "PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE", "PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER", 
        "PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER", "PROVIDER_ENUMERATION_DATE", "LAST_UPDATE_DATE", 
        "NPI_DEACTIVATION_REASON_CODE", "NPI_DEACTIVATION_DATE", "NPI_REACTIVATION_DATE", "PROVIDER_SEX_CODE", 
        "AUTHORIZED_OFFICIAL_LAST_NAME", "AUTHORIZED_OFFICIAL_FIRST_NAME", "AUTHORIZED_OFFICIAL_MIDDLE_NAME", 
        "AUTHORIZED_OFFICIAL_TITLE_OR_POSITION", "AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER", "IS_SOLE_PROPRIETOR", 
        "IS_ORGANIZATION_SUBPART", "PARENT_ORGANIZATION_LBN", "PARENT_ORGANIZATION_TIN", 
        "AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT", "AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT", 
        "AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT", "CERTIFICATION_DATE"
    ],
    "PROVIDER_NPI_ADDRESS": [
        "PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS", "PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS",
        "PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME", "PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME",
        "PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE", "PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE_PLUS4",
        "PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE", "PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER",
        "PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER"
    ],
    "PROVIDER_NPI_TAXONOMY": [
        "HEALTHCARE_PROVIDER_TAXONOMY_CODE", "HEALTHCARE_PROVIDER_TAXONOMY_GROUP", "PROVIDER_LICENSE_NUMBER",
        "PROVIDER_LICENSE_NUMBER_STATE_CODE", "HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH"
    ],
    "PROVIDER_NPI_OTHER_IDS": [
        "OTHER_PROVIDER_IDENTIFIER", "OTHER_PROVIDER_IDENTIFIER_TYPE_CODE", "OTHER_PROVIDER_IDENTIFIER_STATE",
        "OTHER_PROVIDER_IDENTIFIER_ISSUER"
    ],
    "PROVIDER_NPI_XREF": [
        "PROVIDER_ID", "PROVIDER_ENUMERATION_DATE", "NPI_DEACTIVATION_DATE", "IS_NPI_ACTIVE"
    ]
}

# Table configuration for primary key columns
PRIMARY_KEY_COLUMNS: Dict[str, List[str]] = {
    "PROVIDER_NPI": ["NPI"],
    "PROVIDER_NPI_ADDRESS": ["NPI", "PROVIDER_ADDRESS_TYPE"],
    "PROVIDER_NPI_TAXONOMY": ["NPI", "HEALTHCARE_PROVIDER_TAXONOMY_CODE_SEQ_ID"],
    "PROVIDER_NPI_OTHER_IDS": ["NPI", "OTHER_PROVIDER_IDENTIFIER_SEQ_ID"],
    "PROVIDER_NPI_XREF": ["NPI"]
}

# List of tables to process
TABLES_TO_PROCESS: List[str] = [
    "PROVIDER_NPI",
    "PROVIDER_NPI_ADDRESS",
    "PROVIDER_NPI_TAXONOMY",
    "PROVIDER_NPI_OTHER_IDS",
    "PROVIDER_NPI_XREF",
]

# Metadata column names
METADATA_COLUMNS: List[str] = [
    "META_PROGRAM_NAME", 
    "META_SUBJECT_AREA", 
    "META_BATCH_ID", 
    "META_DATE_INSERT", 
    "META_DATE_UPDATE", 
    "META_UPD_BATCH_ID"
]

# Default metadata values
DEFAULT_METADATA_VALUES: List[str] = [
    "'{program_name}'", 
    "'{subject_area}'", 
    "{audit_batch_id}", 
    "CURRENT_TIMESTAMP()", 
    "NULL", 
    "NULL"
]

# Metadata update expressions
METADATA_UPDATE_EXPRESSIONS: List[str] = [
    "g.META_DATE_UPDATE = CURRENT_TIMESTAMP()",
    "g.META_UPD_BATCH_ID = s.META_BATCH_ID"
]