"Code" AS CODE,
"Grouping" AS GROUPING,
"Classification" AS CLASSIFICATION,
"Specialization" AS SPECIALIZATION,
"Definition" AS DEFINITION,
"Notes" AS NOTES,
"Display Name" AS DISPLAY_NAME,
"Section" AS SECTION,