INSERT INTO {silver_db}.{silver_schema}.PROVIDER_NPI_XREF (
    META_PROGRAM_NAME, META_SUBJECT_AREA, META_BATCH_ID, META_DATE_INSERT, META_DATE_UPDATE, META_UPD_BATCH_ID,
    PROVIDER_ID, NPI, PROVIDER_ENUMERATION_DATE, NPI_DEACTIVATION_DATE, IS_NPI_ACTIVE
)
SELECT 
    '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
    NPI, -- PROVIDER_ID: Internal provider ID - Same as NPI
    NPI,
    PROVIDER_ENUMERATION_DATE, -- NPI effective begin date
    -- TRANSFORMATION: NPI effective end date - CASE WHEN NPI_DEACTIVATION_DATE IS NULL THEN '2299-12-31' ELSE NPI_DEACTIVATION_DATE END
    CASE 
        WHEN NPI_DEACTIVATION_DATE IS NULL THEN '2299-12-31' 
        ELSE NPI_DEACTIVATION_DATE 
    END,
    -- TRANSFORMATION: NPI active indicator - CASE WHEN end_date = '2299-12-31' THEN 'Y' ELSE 'N' END
    CASE 
        WHEN NPI_DEACTIVATION_DATE IS NULL THEN 'Y'
        WHEN NPI_DEACTIVATION_DATE = '2299-12-31' THEN 'Y'
        ELSE 'N' 
    END
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL;