INSERT INTO {silver_db}.{silver_schema}.PROVIDER_NPI_ADDRESS (
    META_PROGRAM_NAME, META_SUBJECT_AREA, META_BATCH_ID, META_DATE_INSERT, META_DATE_UPDATE, META_UPD_BATCH_ID,
    NPI, PROVIDER_ADDRESS_TYPE, PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS, PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS,
    PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME, PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME, 
    PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE, PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE_PLUS4,
    PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE, PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER, 
    PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER
)
-- Mailing Address (M) - Only if mailing address exists
SELECT 
    '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
    NPI, -- PRIMARY KEY component 1
    'M', -- PRIMARY KEY component 2: Mailing address type
    PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS,
    PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS,
    PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME,
    -- TRANSFORMATION: State validation - NULL if length != 2
    CASE 
        WHEN LENGTH(PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME) = 2 
        THEN PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME 
        ELSE NULL 
    END,
    -- TRANSFORMATION: ZIP extraction - first 5 digits
    SUBSTRING(PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE, 1, 5),
    -- TRANSFORMATION: ZIP+4 extraction - positions 7-10 if length > 5
    CASE 
        WHEN LENGTH(PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE) > 5 
        THEN SUBSTRING(PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE, 7, 4) 
        ELSE NULL 
    END,
    PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE,
    -- TRANSFORMATION: Phone validation - NULL if length != 10
    CASE 
        WHEN LENGTH(REGEXP_REPLACE(PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER, '[^0-9]', '')) = 10 
        THEN PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER 
        ELSE NULL 
    END,
    -- TRANSFORMATION: Fax validation - NULL if length != 10
    CASE 
        WHEN LENGTH(REGEXP_REPLACE(PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER, '[^0-9]', '')) = 10 
        THEN PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER 
        ELSE NULL 
    END
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' 
  AND NPI IS NOT NULL 
  AND PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS IS NOT NULL
  AND TRIM(PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS) != ''

UNION ALL

-- Service Location Address (S) - Only if service address exists
SELECT 
    '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
    NPI, -- PRIMARY KEY component 1
    'S', -- PRIMARY KEY component 2: Service location address type
    PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS,
    PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS,
    PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME,
    -- TRANSFORMATION: State validation - NULL if length != 2
    CASE 
        WHEN LENGTH(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME) = 2 
        THEN PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME 
        ELSE NULL 
    END,
    -- TRANSFORMATION: ZIP extraction - first 5 digits
    SUBSTRING(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE, 1, 5),
    -- TRANSFORMATION: ZIP+4 extraction - positions 7-10 if length > 5
    CASE 
        WHEN LENGTH(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE) > 5 
        THEN SUBSTRING(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE, 7, 4) 
        ELSE NULL 
    END,
    PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE,
    -- TRANSFORMATION: Phone validation - NULL if length != 10
    CASE 
        WHEN LENGTH(REGEXP_REPLACE(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER, '[^0-9]', '')) = 10 
        THEN PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER 
        ELSE NULL 
    END,
    -- TRANSFORMATION: Fax validation - NULL if length != 10
    CASE 
        WHEN LENGTH(REGEXP_REPLACE(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER, '[^0-9]', '')) = 10 
        THEN PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER 
        ELSE NULL 
    END
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' 
  AND NPI IS NOT NULL 
  AND PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS IS NOT NULL
  AND TRIM(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS) != '';