INSERT INTO {silver_db}.{silver_schema}.PROVIDER_NPI (
    META_PROGRAM_NAME, META_SUBJECT_AREA, META_BATCH_ID, META_DATE_INSERT, META_DATE_UPDATE, META_UPD_BATCH_ID,
    NPI, ENTITY_TYPE_CODE, REPLACEMENT_NPI, EMPLOYER_IDENTIFICATION_NUMBER, PROVIDER_ORGANIZATION_NAME,
    PROVIDER_LAST_NAME, PROVIDER_FIRST_NAME, PROVIDER_MIDDLE_NAME, PROVIDER_NAME_PREFIX_TEXT, PROVIDER_NAME_SUFFIX_TEXT,
    PROVIDER_CREDENTIAL_TEXT, PROVIDER_OTHER_ORGANIZATION_NAME, PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE,
    PROVIDER_OTHER_LAST_NAME, PROVIDER_OTHER_FIRST_NAME, PROVIDER_OTHER_MIDDLE_NAME, PROVIDER_OTHER_NAME_PREFIX_TEXT,
    PROVIDER_OTHER_NAME_SUFFIX_TEXT, PROVIDER_OTHER_CREDENTIAL_TEXT, PROVIDER_OTHER_LAST_NAME_TYPE_CODE,
    PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS, PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS,
    PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME, PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME,
    PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE, PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE,
    PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER, PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER,
    PROVIDER_ENUMERATION_DATE, LAST_UPDATE_DATE, NPI_DEACTIVATION_REASON_CODE, NPI_DEACTIVATION_DATE, 
    NPI_REACTIVATION_DATE, PROVIDER_SEX_CODE, AUTHORIZED_OFFICIAL_LAST_NAME, AUTHORIZED_OFFICIAL_FIRST_NAME,
    AUTHORIZED_OFFICIAL_MIDDLE_NAME, AUTHORIZED_OFFICIAL_TITLE_OR_POSITION, AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER,
    IS_SOLE_PROPRIETOR, IS_ORGANIZATION_SUBPART, PARENT_ORGANIZATION_LBN, PARENT_ORGANIZATION_TIN,
    AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT, AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT, AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT,
    CERTIFICATION_DATE
)
SELECT 
    '{program_name}', '{subject_area}', {audit_batch_id}, CURRENT_TIMESTAMP(), NULL,NULL,
    NPI, -- PRIMARY KEY: National Provider Identifier
    ENTITY_TYPE_CODE,
    REPLACEMENT_NPI,
    EMPLOYER_IDENTIFICATION_NUMBER,
    -- TRANSFORMATION: Full name based on entity type
   CASE 
    WHEN ENTITY_TYPE_CODE = '1' THEN 
        CONCAT(
            COALESCE(PROVIDER_LAST_NAME, ''), 
            ', ', 
            COALESCE(PROVIDER_FIRST_NAME, ''),
            CASE WHEN PROVIDER_MIDDLE_NAME IS NOT NULL THEN CONCAT(' ', PROVIDER_MIDDLE_NAME) ELSE '' END
        )
    WHEN ENTITY_TYPE_CODE = '2' THEN PROVIDER_ORGANIZATION_NAME
    ELSE PROVIDER_ORGANIZATION_NAME
    END,
    PROVIDER_LAST_NAME,
    PROVIDER_FIRST_NAME,
    PROVIDER_MIDDLE_NAME,
    PROVIDER_NAME_PREFIX_TEXT,
    PROVIDER_NAME_SUFFIX_TEXT,
    PROVIDER_CREDENTIAL_TEXT,
    PROVIDER_OTHER_ORGANIZATION_NAME,
    PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE,
    PROVIDER_OTHER_LAST_NAME,
    PROVIDER_OTHER_FIRST_NAME,
    PROVIDER_OTHER_MIDDLE_NAME,
    PROVIDER_OTHER_NAME_PREFIX_TEXT,
    PROVIDER_OTHER_NAME_SUFFIX_TEXT,
    PROVIDER_OTHER_CREDENTIAL_TEXT,
    PROVIDER_OTHER_LAST_NAME_TYPE_CODE,
    PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS,
    PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS,
    PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME,
    PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME,
    PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE,
    PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE,
    -- TRANSFORMATION: Phone validation - NULL if length != 10
    CASE 
        WHEN LENGTH(REGEXP_REPLACE(PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER, '[^0-9]', '')) = 10 
        THEN PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER 
        ELSE NULL 
    END,
    -- TRANSFORMATION: Fax validation - NULL if length != 10
    CASE 
        WHEN LENGTH(REGEXP_REPLACE(PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER, '[^0-9]', '')) = 10 
        THEN PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER 
        ELSE NULL 
    END,
    PROVIDER_ENUMERATION_DATE,
    LAST_UPDATE_DATE,
    NPI_DEACTIVATION_REASON_CODE,
    NPI_DEACTIVATION_DATE,
    NPI_REACTIVATION_DATE,
    PROVIDER_SEX_CODE,
    AUTHORIZED_OFFICIAL_LAST_NAME,
    AUTHORIZED_OFFICIAL_FIRST_NAME,
    AUTHORIZED_OFFICIAL_MIDDLE_NAME,
    AUTHORIZED_OFFICIAL_TITLE_OR_POSITION,
    -- TRANSFORMATION: Phone validation - NULL if length != 10
    CASE 
        WHEN LENGTH(REGEXP_REPLACE(AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER, '[^0-9]', '')) = 10 
        THEN AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER 
        ELSE NULL 
    END,
    IS_SOLE_PROPRIETOR,
    IS_ORGANIZATION_SUBPART,
    PARENT_ORGANIZATION_LBN,
    PARENT_ORGANIZATION_TIN,
    AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT,
    AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT,
    AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT,
    CERTIFICATION_DATE
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = {audit_batch_id} AND NPI IS NOT NULL;