INSERT INTO {silver_db}.{silver_schema}.PROVIDER_NPI_TAXONOMY (
    META_PROGRAM_NAME, META_SUBJECT_AREA, META_BATCH_ID, META_DATE_INSERT, META_DATE_UPDATE, META_UPD_BATCH_ID,
    NPI, HEALTHCARE_PROVIDER_TAXONOMY_CODE_SEQ_ID, HEALTHCARE_PROVIDER_TAXONOMY_CODE, HEALTHCARE_PROVIDER_TAXONOMY_GROUP,
    PROVIDER_LICENSE_NUMBER, PROVIDER_LICENSE_NUMBER_STATE_CODE, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH
)
-- UNPIVOT TRANSFORMATION: Composite PRIMARY KEY
SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, -- PRIMARY KEY component 1
       '1', -- PRIMARY KEY component 2: Sequence ID from column name
       HEALTHCARE_PROVIDER_TAXONOMY_CODE_1, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_1,
       PROVIDER_LICENSE_NUMBER_1, PROVIDER_LICENSE_NUMBER_STATE_CODE_1, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_1
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '2', HEALTHCARE_PROVIDER_TAXONOMY_CODE_2, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_2,
       PROVIDER_LICENSE_NUMBER_2, PROVIDER_LICENSE_NUMBER_STATE_CODE_2, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_2
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_2 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '3', HEALTHCARE_PROVIDER_TAXONOMY_CODE_3, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_3,
       PROVIDER_LICENSE_NUMBER_3, PROVIDER_LICENSE_NUMBER_STATE_CODE_3, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_3
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_3 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '4', HEALTHCARE_PROVIDER_TAXONOMY_CODE_4, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_4,
       PROVIDER_LICENSE_NUMBER_4, PROVIDER_LICENSE_NUMBER_STATE_CODE_4, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_4
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_4 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '5', HEALTHCARE_PROVIDER_TAXONOMY_CODE_5, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_5,
       PROVIDER_LICENSE_NUMBER_5, PROVIDER_LICENSE_NUMBER_STATE_CODE_5, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_5
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_5 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '6', HEALTHCARE_PROVIDER_TAXONOMY_CODE_6, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_6,
       PROVIDER_LICENSE_NUMBER_6, PROVIDER_LICENSE_NUMBER_STATE_CODE_6, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_6
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_6 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '7', HEALTHCARE_PROVIDER_TAXONOMY_CODE_7, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_7,
       PROVIDER_LICENSE_NUMBER_7, PROVIDER_LICENSE_NUMBER_STATE_CODE_7, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_7
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_7 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '8', HEALTHCARE_PROVIDER_TAXONOMY_CODE_8, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_8,
       PROVIDER_LICENSE_NUMBER_8, PROVIDER_LICENSE_NUMBER_STATE_CODE_8, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_8
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_8 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '9', HEALTHCARE_PROVIDER_TAXONOMY_CODE_9, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_9,
       PROVIDER_LICENSE_NUMBER_9, PROVIDER_LICENSE_NUMBER_STATE_CODE_9, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_9
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_9 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '10', HEALTHCARE_PROVIDER_TAXONOMY_CODE_10, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_10,
       PROVIDER_LICENSE_NUMBER_10, PROVIDER_LICENSE_NUMBER_STATE_CODE_10, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_10
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_10 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '11', HEALTHCARE_PROVIDER_TAXONOMY_CODE_11, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_11,
       PROVIDER_LICENSE_NUMBER_11, PROVIDER_LICENSE_NUMBER_STATE_CODE_11, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_11
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_11 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '12', HEALTHCARE_PROVIDER_TAXONOMY_CODE_12, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_12,
       PROVIDER_LICENSE_NUMBER_12, PROVIDER_LICENSE_NUMBER_STATE_CODE_12, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_12
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_12 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '13', HEALTHCARE_PROVIDER_TAXONOMY_CODE_13, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_13,
       PROVIDER_LICENSE_NUMBER_13, PROVIDER_LICENSE_NUMBER_STATE_CODE_13, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_13
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_13 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '14', HEALTHCARE_PROVIDER_TAXONOMY_CODE_14, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_14,
       PROVIDER_LICENSE_NUMBER_14, PROVIDER_LICENSE_NUMBER_STATE_CODE_14, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_14
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_14 IS NOT NULL

UNION ALL

SELECT '{program_name}', '{subject_area}', '{audit_batch_id}', CURRENT_TIMESTAMP(), NULL, NULL,
       NPI, '15', HEALTHCARE_PROVIDER_TAXONOMY_CODE_15, HEALTHCARE_PROVIDER_TAXONOMY_GROUP_15,
       PROVIDER_LICENSE_NUMBER_15, PROVIDER_LICENSE_NUMBER_STATE_CODE_15, HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_15
FROM {bronze_db}.{bronze_schema}.{bronze_table}
WHERE META_BATCH_ID = '{audit_batch_id}' AND NPI IS NOT NULL AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_15 IS NOT NULL;