"NPI" AS NPI,
"Entity Type Code" AS ENTITY_TYPE_CODE,
"Replacement NPI" AS REPLACEMENT_NPI,
"Employer Identification Number (EIN)" AS EMPLOYER_IDENTIFICATION_NUMBER,
"Provider Organization Name (Legal Business Name)" AS PROVIDER_ORGANIZATION_NAME,
"Provider Last Name (Legal Name)" AS PROVIDER_LAST_NAME,
"Provider First Name" AS PROVIDER_FIRST_NAME,
"Provider Middle Name" AS PROVIDER_MIDDLE_NAME,
"Provider Name Prefix Text" AS PROVIDER_NAME_PREFIX_TEXT,
"Provider Name Suffix Text" AS PROVIDER_NAME_SUFFIX_TEXT,
"Provider Credential Text" AS PROVIDER_CREDENTIAL_TEXT,
"Provider Other Organization Name" AS PROVIDER_OTHER_ORGANIZATION_NAME,
"Provider Other Organization Name Type Code" AS PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE,
"Provider Other Last Name" AS PROVIDER_OTHER_LAST_NAME,
"Provider Other First Name" AS PROVIDER_OTHER_FIRST_NAME,
"Provider Other Middle Name" AS PROVIDER_OTHER_MIDDLE_NAME,
"Provider Other Name Prefix Text" AS PROVIDER_OTHER_NAME_PREFIX_TEXT,
"Provider Other Name Suffix Text" AS PROVIDER_OTHER_NAME_SUFFIX_TEXT,
"Provider Other Credential Text" AS PROVIDER_OTHER_CREDENTIAL_TEXT,
"Provider Other Last Name Type Code" AS PROVIDER_OTHER_LAST_NAME_TYPE_CODE,
"Provider First Line Business Mailing Address" AS PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS,
"Provider Second Line Business Mailing Address" AS PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS,
"Provider Business Mailing Address City Name" AS PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME,
"Provider Business Mailing Address State Name" AS PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME,
"Provider Business Mailing Address Postal Code" AS PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE,
"Provider Business Mailing Address Country Code (If outside U.S.)" AS PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE,
"Provider Business Mailing Address Telephone Number" AS PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER,
"Provider Business Mailing Address Fax Number" AS PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER,
"Provider First Line Business Practice Location Address" AS PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS,
"Provider Second Line Business Practice Location Address" AS PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS,
"Provider Business Practice Location Address City Name" AS PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME,
"Provider Business Practice Location Address State Name" AS PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME,
"Provider Business Practice Location Address Postal Code" AS PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE,
"Provider Business Practice Location Address Country Code (If outside U.S.)" AS PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE,
"Provider Business Practice Location Address Telephone Number" AS PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER,
"Provider Business Practice Location Address Fax Number" AS PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER,
"Provider Enumeration Date" AS PROVIDER_ENUMERATION_DATE,
"Last Update Date" AS LAST_UPDATE_DATE,
"NPI Deactivation Reason Code" AS NPI_DEACTIVATION_REASON_CODE,
"NPI Deactivation Date" AS NPI_DEACTIVATION_DATE,
"NPI Reactivation Date" AS NPI_REACTIVATION_DATE,
"Provider Sex Code" AS PROVIDER_SEX_CODE,
"Authorized Official Last Name" AS AUTHORIZED_OFFICIAL_LAST_NAME,
"Authorized Official First Name" AS AUTHORIZED_OFFICIAL_FIRST_NAME,
"Authorized Official Middle Name" AS AUTHORIZED_OFFICIAL_MIDDLE_NAME,
"Authorized Official Title or Position" AS AUTHORIZED_OFFICIAL_TITLE_OR_POSITION,
"Authorized Official Telephone Number" AS AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER,
"Healthcare Provider Taxonomy Code_1" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_1,
"Provider License Number_1" AS PROVIDER_LICENSE_NUMBER_1,
"Provider License Number State Code_1" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_1,
"Healthcare Provider Primary Taxonomy Switch_1" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_1,
"Healthcare Provider Taxonomy Code_2" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_2,
"Provider License Number_2" AS PROVIDER_LICENSE_NUMBER_2,
"Provider License Number State Code_2" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_2,
"Healthcare Provider Primary Taxonomy Switch_2" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_2,
"Healthcare Provider Taxonomy Code_3" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_3,
"Provider License Number_3" AS PROVIDER_LICENSE_NUMBER_3,
"Provider License Number State Code_3" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_3,
"Healthcare Provider Primary Taxonomy Switch_3" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_3,
"Healthcare Provider Taxonomy Code_4" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_4,
"Provider License Number_4" AS PROVIDER_LICENSE_NUMBER_4,
"Provider License Number State Code_4" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_4,
"Healthcare Provider Primary Taxonomy Switch_4" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_4,
"Healthcare Provider Taxonomy Code_5" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_5,
"Provider License Number_5" AS PROVIDER_LICENSE_NUMBER_5,
"Provider License Number State Code_5" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_5,
"Healthcare Provider Primary Taxonomy Switch_5" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_5,
"Healthcare Provider Taxonomy Code_6" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_6,
"Provider License Number_6" AS PROVIDER_LICENSE_NUMBER_6,
"Provider License Number State Code_6" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_6,
"Healthcare Provider Primary Taxonomy Switch_6" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_6,
"Healthcare Provider Taxonomy Code_7" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_7,
"Provider License Number_7" AS PROVIDER_LICENSE_NUMBER_7,
"Provider License Number State Code_7" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_7,
"Healthcare Provider Primary Taxonomy Switch_7" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_7,
"Healthcare Provider Taxonomy Code_8" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_8,
"Provider License Number_8" AS PROVIDER_LICENSE_NUMBER_8,
"Provider License Number State Code_8" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_8,
"Healthcare Provider Primary Taxonomy Switch_8" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_8,
"Healthcare Provider Taxonomy Code_9" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_9,
"Provider License Number_9" AS PROVIDER_LICENSE_NUMBER_9,
"Provider License Number State Code_9" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_9,
"Healthcare Provider Primary Taxonomy Switch_9" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_9,
"Healthcare Provider Taxonomy Code_10" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_10,
"Provider License Number_10" AS PROVIDER_LICENSE_NUMBER_10,
"Provider License Number State Code_10" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_10,
"Healthcare Provider Primary Taxonomy Switch_10" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_10,
"Healthcare Provider Taxonomy Code_11" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_11,
"Provider License Number_11" AS PROVIDER_LICENSE_NUMBER_11,
"Provider License Number State Code_11" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_11,
"Healthcare Provider Primary Taxonomy Switch_11" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_11,
"Healthcare Provider Taxonomy Code_12" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_12,
"Provider License Number_12" AS PROVIDER_LICENSE_NUMBER_12,
"Provider License Number State Code_12" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_12,
"Healthcare Provider Primary Taxonomy Switch_12" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_12,
"Healthcare Provider Taxonomy Code_13" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_13,
"Provider License Number_13" AS PROVIDER_LICENSE_NUMBER_13,
"Provider License Number State Code_13" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_13,
"Healthcare Provider Primary Taxonomy Switch_13" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_13,
"Healthcare Provider Taxonomy Code_14" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_14,
"Provider License Number_14" AS PROVIDER_LICENSE_NUMBER_14,
"Provider License Number State Code_14" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_14,
"Healthcare Provider Primary Taxonomy Switch_14" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_14,
"Healthcare Provider Taxonomy Code_15" AS HEALTHCARE_PROVIDER_TAXONOMY_CODE_15,
"Provider License Number_15" AS PROVIDER_LICENSE_NUMBER_15,
"Provider License Number State Code_15" AS PROVIDER_LICENSE_NUMBER_STATE_CODE_15,
"Healthcare Provider Primary Taxonomy Switch_15" AS HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_15,
"Other Provider Identifier_1" AS OTHER_PROVIDER_IDENTIFIER_1,
"Other Provider Identifier Type Code_1" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_1,
"Other Provider Identifier State_1" AS OTHER_PROVIDER_IDENTIFIER_STATE_1,
"Other Provider Identifier Issuer_1" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_1,
"Other Provider Identifier_2" AS OTHER_PROVIDER_IDENTIFIER_2,
"Other Provider Identifier Type Code_2" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_2,
"Other Provider Identifier State_2" AS OTHER_PROVIDER_IDENTIFIER_STATE_2,
"Other Provider Identifier Issuer_2" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_2,
"Other Provider Identifier_3" AS OTHER_PROVIDER_IDENTIFIER_3,
"Other Provider Identifier Type Code_3" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_3,
"Other Provider Identifier State_3" AS OTHER_PROVIDER_IDENTIFIER_STATE_3,
"Other Provider Identifier Issuer_3" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_3,
"Other Provider Identifier_4" AS OTHER_PROVIDER_IDENTIFIER_4,
"Other Provider Identifier Type Code_4" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_4,
"Other Provider Identifier State_4" AS OTHER_PROVIDER_IDENTIFIER_STATE_4,
"Other Provider Identifier Issuer_4" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_4,
"Other Provider Identifier_5" AS OTHER_PROVIDER_IDENTIFIER_5,
"Other Provider Identifier Type Code_5" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_5,
"Other Provider Identifier State_5" AS OTHER_PROVIDER_IDENTIFIER_STATE_5,
"Other Provider Identifier Issuer_5" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_5,
"Other Provider Identifier_6" AS OTHER_PROVIDER_IDENTIFIER_6,
"Other Provider Identifier Type Code_6" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_6,
"Other Provider Identifier State_6" AS OTHER_PROVIDER_IDENTIFIER_STATE_6,
"Other Provider Identifier Issuer_6" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_6,
"Other Provider Identifier_7" AS OTHER_PROVIDER_IDENTIFIER_7,
"Other Provider Identifier Type Code_7" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_7,
"Other Provider Identifier State_7" AS OTHER_PROVIDER_IDENTIFIER_STATE_7,
"Other Provider Identifier Issuer_7" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_7,
"Other Provider Identifier_8" AS OTHER_PROVIDER_IDENTIFIER_8,
"Other Provider Identifier Type Code_8" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_8,
"Other Provider Identifier State_8" AS OTHER_PROVIDER_IDENTIFIER_STATE_8,
"Other Provider Identifier Issuer_8" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_8,
"Other Provider Identifier_9" AS OTHER_PROVIDER_IDENTIFIER_9,
"Other Provider Identifier Type Code_9" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_9,
"Other Provider Identifier State_9" AS OTHER_PROVIDER_IDENTIFIER_STATE_9,
"Other Provider Identifier Issuer_9" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_9,
"Other Provider Identifier_10" AS OTHER_PROVIDER_IDENTIFIER_10,
"Other Provider Identifier Type Code_10" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_10,
"Other Provider Identifier State_10" AS OTHER_PROVIDER_IDENTIFIER_STATE_10,
"Other Provider Identifier Issuer_10" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_10,
"Other Provider Identifier_11" AS OTHER_PROVIDER_IDENTIFIER_11,
"Other Provider Identifier Type Code_11" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_11,
"Other Provider Identifier State_11" AS OTHER_PROVIDER_IDENTIFIER_STATE_11,
"Other Provider Identifier Issuer_11" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_11,
"Other Provider Identifier_12" AS OTHER_PROVIDER_IDENTIFIER_12,
"Other Provider Identifier Type Code_12" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_12,
"Other Provider Identifier State_12" AS OTHER_PROVIDER_IDENTIFIER_STATE_12,
"Other Provider Identifier Issuer_12" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_12,
"Other Provider Identifier_13" AS OTHER_PROVIDER_IDENTIFIER_13,
"Other Provider Identifier Type Code_13" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_13,
"Other Provider Identifier State_13" AS OTHER_PROVIDER_IDENTIFIER_STATE_13,
"Other Provider Identifier Issuer_13" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_13,
"Other Provider Identifier_14" AS OTHER_PROVIDER_IDENTIFIER_14,
"Other Provider Identifier Type Code_14" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_14,
"Other Provider Identifier State_14" AS OTHER_PROVIDER_IDENTIFIER_STATE_14,
"Other Provider Identifier Issuer_14" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_14,
"Other Provider Identifier_15" AS OTHER_PROVIDER_IDENTIFIER_15,
"Other Provider Identifier Type Code_15" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_15,
"Other Provider Identifier State_15" AS OTHER_PROVIDER_IDENTIFIER_STATE_15,
"Other Provider Identifier Issuer_15" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_15,
"Other Provider Identifier_16" AS OTHER_PROVIDER_IDENTIFIER_16,
"Other Provider Identifier Type Code_16" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_16,
"Other Provider Identifier State_16" AS OTHER_PROVIDER_IDENTIFIER_STATE_16,
"Other Provider Identifier Issuer_16" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_16,
"Other Provider Identifier_17" AS OTHER_PROVIDER_IDENTIFIER_17,
"Other Provider Identifier Type Code_17" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_17,
"Other Provider Identifier State_17" AS OTHER_PROVIDER_IDENTIFIER_STATE_17,
"Other Provider Identifier Issuer_17" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_17,
"Other Provider Identifier_18" AS OTHER_PROVIDER_IDENTIFIER_18,
"Other Provider Identifier Type Code_18" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_18,
"Other Provider Identifier State_18" AS OTHER_PROVIDER_IDENTIFIER_STATE_18,
"Other Provider Identifier Issuer_18" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_18,
"Other Provider Identifier_19" AS OTHER_PROVIDER_IDENTIFIER_19,
"Other Provider Identifier Type Code_19" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_19,
"Other Provider Identifier State_19" AS OTHER_PROVIDER_IDENTIFIER_STATE_19,
"Other Provider Identifier Issuer_19" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_19,
"Other Provider Identifier_20" AS OTHER_PROVIDER_IDENTIFIER_20,
"Other Provider Identifier Type Code_20" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_20,
"Other Provider Identifier State_20" AS OTHER_PROVIDER_IDENTIFIER_STATE_20,
"Other Provider Identifier Issuer_20" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_20,
"Other Provider Identifier_21" AS OTHER_PROVIDER_IDENTIFIER_21,
"Other Provider Identifier Type Code_21" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_21,
"Other Provider Identifier State_21" AS OTHER_PROVIDER_IDENTIFIER_STATE_21,
"Other Provider Identifier Issuer_21" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_21,
"Other Provider Identifier_22" AS OTHER_PROVIDER_IDENTIFIER_22,
"Other Provider Identifier Type Code_22" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_22,
"Other Provider Identifier State_22" AS OTHER_PROVIDER_IDENTIFIER_STATE_22,
"Other Provider Identifier Issuer_22" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_22,
"Other Provider Identifier_23" AS OTHER_PROVIDER_IDENTIFIER_23,
"Other Provider Identifier Type Code_23" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_23,
"Other Provider Identifier State_23" AS OTHER_PROVIDER_IDENTIFIER_STATE_23,
"Other Provider Identifier Issuer_23" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_23,
"Other Provider Identifier_24" AS OTHER_PROVIDER_IDENTIFIER_24,
"Other Provider Identifier Type Code_24" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_24,
"Other Provider Identifier State_24" AS OTHER_PROVIDER_IDENTIFIER_STATE_24,
"Other Provider Identifier Issuer_24" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_24,
"Other Provider Identifier_25" AS OTHER_PROVIDER_IDENTIFIER_25,
"Other Provider Identifier Type Code_25" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_25,
"Other Provider Identifier State_25" AS OTHER_PROVIDER_IDENTIFIER_STATE_25,
"Other Provider Identifier Issuer_25" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_25,
"Other Provider Identifier_26" AS OTHER_PROVIDER_IDENTIFIER_26,
"Other Provider Identifier Type Code_26" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_26,
"Other Provider Identifier State_26" AS OTHER_PROVIDER_IDENTIFIER_STATE_26,
"Other Provider Identifier Issuer_26" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_26,
"Other Provider Identifier_27" AS OTHER_PROVIDER_IDENTIFIER_27,
"Other Provider Identifier Type Code_27" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_27,
"Other Provider Identifier State_27" AS OTHER_PROVIDER_IDENTIFIER_STATE_27,
"Other Provider Identifier Issuer_27" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_27,
"Other Provider Identifier_28" AS OTHER_PROVIDER_IDENTIFIER_28,
"Other Provider Identifier Type Code_28" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_28,
"Other Provider Identifier State_28" AS OTHER_PROVIDER_IDENTIFIER_STATE_28,
"Other Provider Identifier Issuer_28" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_28,
"Other Provider Identifier_29" AS OTHER_PROVIDER_IDENTIFIER_29,
"Other Provider Identifier Type Code_29" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_29,
"Other Provider Identifier State_29" AS OTHER_PROVIDER_IDENTIFIER_STATE_29,
"Other Provider Identifier Issuer_29" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_29,
"Other Provider Identifier_30" AS OTHER_PROVIDER_IDENTIFIER_30,
"Other Provider Identifier Type Code_30" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_30,
"Other Provider Identifier State_30" AS OTHER_PROVIDER_IDENTIFIER_STATE_30,
"Other Provider Identifier Issuer_30" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_30,
"Other Provider Identifier_31" AS OTHER_PROVIDER_IDENTIFIER_31,
"Other Provider Identifier Type Code_31" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_31,
"Other Provider Identifier State_31" AS OTHER_PROVIDER_IDENTIFIER_STATE_31,
"Other Provider Identifier Issuer_31" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_31,
"Other Provider Identifier_32" AS OTHER_PROVIDER_IDENTIFIER_32,
"Other Provider Identifier Type Code_32" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_32,
"Other Provider Identifier State_32" AS OTHER_PROVIDER_IDENTIFIER_STATE_32,
"Other Provider Identifier Issuer_32" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_32,
"Other Provider Identifier_33" AS OTHER_PROVIDER_IDENTIFIER_33,
"Other Provider Identifier Type Code_33" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_33,
"Other Provider Identifier State_33" AS OTHER_PROVIDER_IDENTIFIER_STATE_33,
"Other Provider Identifier Issuer_33" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_33,
"Other Provider Identifier_34" AS OTHER_PROVIDER_IDENTIFIER_34,
"Other Provider Identifier Type Code_34" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_34,
"Other Provider Identifier State_34" AS OTHER_PROVIDER_IDENTIFIER_STATE_34,
"Other Provider Identifier Issuer_34" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_34,
"Other Provider Identifier_35" AS OTHER_PROVIDER_IDENTIFIER_35,
"Other Provider Identifier Type Code_35" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_35,
"Other Provider Identifier State_35" AS OTHER_PROVIDER_IDENTIFIER_STATE_35,
"Other Provider Identifier Issuer_35" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_35,
"Other Provider Identifier_36" AS OTHER_PROVIDER_IDENTIFIER_36,
"Other Provider Identifier Type Code_36" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_36,
"Other Provider Identifier State_36" AS OTHER_PROVIDER_IDENTIFIER_STATE_36,
"Other Provider Identifier Issuer_36" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_36,
"Other Provider Identifier_37" AS OTHER_PROVIDER_IDENTIFIER_37,
"Other Provider Identifier Type Code_37" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_37,
"Other Provider Identifier State_37" AS OTHER_PROVIDER_IDENTIFIER_STATE_37,
"Other Provider Identifier Issuer_37" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_37,
"Other Provider Identifier_38" AS OTHER_PROVIDER_IDENTIFIER_38,
"Other Provider Identifier Type Code_38" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_38,
"Other Provider Identifier State_38" AS OTHER_PROVIDER_IDENTIFIER_STATE_38,
"Other Provider Identifier Issuer_38" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_38,
"Other Provider Identifier_39" AS OTHER_PROVIDER_IDENTIFIER_39,
"Other Provider Identifier Type Code_39" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_39,
"Other Provider Identifier State_39" AS OTHER_PROVIDER_IDENTIFIER_STATE_39,
"Other Provider Identifier Issuer_39" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_39,
"Other Provider Identifier_40" AS OTHER_PROVIDER_IDENTIFIER_40,
"Other Provider Identifier Type Code_40" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_40,
"Other Provider Identifier State_40" AS OTHER_PROVIDER_IDENTIFIER_STATE_40,
"Other Provider Identifier Issuer_40" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_40,
"Other Provider Identifier_41" AS OTHER_PROVIDER_IDENTIFIER_41,
"Other Provider Identifier Type Code_41" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_41,
"Other Provider Identifier State_41" AS OTHER_PROVIDER_IDENTIFIER_STATE_41,
"Other Provider Identifier Issuer_41" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_41,
"Other Provider Identifier_42" AS OTHER_PROVIDER_IDENTIFIER_42,
"Other Provider Identifier Type Code_42" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_42,
"Other Provider Identifier State_42" AS OTHER_PROVIDER_IDENTIFIER_STATE_42,
"Other Provider Identifier Issuer_42" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_42,
"Other Provider Identifier_43" AS OTHER_PROVIDER_IDENTIFIER_43,
"Other Provider Identifier Type Code_43" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_43,
"Other Provider Identifier State_43" AS OTHER_PROVIDER_IDENTIFIER_STATE_43,
"Other Provider Identifier Issuer_43" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_43,
"Other Provider Identifier_44" AS OTHER_PROVIDER_IDENTIFIER_44,
"Other Provider Identifier Type Code_44" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_44,
"Other Provider Identifier State_44" AS OTHER_PROVIDER_IDENTIFIER_STATE_44,
"Other Provider Identifier Issuer_44" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_44,
"Other Provider Identifier_45" AS OTHER_PROVIDER_IDENTIFIER_45,
"Other Provider Identifier Type Code_45" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_45,
"Other Provider Identifier State_45" AS OTHER_PROVIDER_IDENTIFIER_STATE_45,
"Other Provider Identifier Issuer_45" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_45,
"Other Provider Identifier_46" AS OTHER_PROVIDER_IDENTIFIER_46,
"Other Provider Identifier Type Code_46" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_46,
"Other Provider Identifier State_46" AS OTHER_PROVIDER_IDENTIFIER_STATE_46,
"Other Provider Identifier Issuer_46" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_46,
"Other Provider Identifier_47" AS OTHER_PROVIDER_IDENTIFIER_47,
"Other Provider Identifier Type Code_47" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_47,
"Other Provider Identifier State_47" AS OTHER_PROVIDER_IDENTIFIER_STATE_47,
"Other Provider Identifier Issuer_47" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_47,
"Other Provider Identifier_48" AS OTHER_PROVIDER_IDENTIFIER_48,
"Other Provider Identifier Type Code_48" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_48,
"Other Provider Identifier State_48" AS OTHER_PROVIDER_IDENTIFIER_STATE_48,
"Other Provider Identifier Issuer_48" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_48,
"Other Provider Identifier_49" AS OTHER_PROVIDER_IDENTIFIER_49,
"Other Provider Identifier Type Code_49" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_49,
"Other Provider Identifier State_49" AS OTHER_PROVIDER_IDENTIFIER_STATE_49,
"Other Provider Identifier Issuer_49" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_49,
"Other Provider Identifier_50" AS OTHER_PROVIDER_IDENTIFIER_50,
"Other Provider Identifier Type Code_50" AS OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_50,
"Other Provider Identifier State_50" AS OTHER_PROVIDER_IDENTIFIER_STATE_50,
"Other Provider Identifier Issuer_50" AS OTHER_PROVIDER_IDENTIFIER_ISSUER_50,
"Is Sole Proprietor" AS IS_SOLE_PROPRIETOR,
"Is Organization Subpart" AS IS_ORGANIZATION_SUBPART,
"Parent Organization LBN" AS PARENT_ORGANIZATION_LBN,
"Parent Organization TIN" AS PARENT_ORGANIZATION_TIN,
"Authorized Official Name Prefix Text" AS AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT,
"Authorized Official Name Suffix Text" AS AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT,
"Authorized Official Credential Text" AS AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT,
"Healthcare Provider Taxonomy Group_1" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_1,
"Healthcare Provider Taxonomy Group_2" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_2,
"Healthcare Provider Taxonomy Group_3" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_3,
"Healthcare Provider Taxonomy Group_4" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_4,
"Healthcare Provider Taxonomy Group_5" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_5,
"Healthcare Provider Taxonomy Group_6" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_6,
"Healthcare Provider Taxonomy Group_7" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_7,
"Healthcare Provider Taxonomy Group_8" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_8,
"Healthcare Provider Taxonomy Group_9" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_9,
"Healthcare Provider Taxonomy Group_10" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_10,
"Healthcare Provider Taxonomy Group_11" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_11,
"Healthcare Provider Taxonomy Group_12" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_12,
"Healthcare Provider Taxonomy Group_13" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_13,
"Healthcare Provider Taxonomy Group_14" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_14,
"Healthcare Provider Taxonomy Group_15" AS HEALTHCARE_PROVIDER_TAXONOMY_GROUP_15,
"Certification Date" AS CERTIFICATION_DATE,